LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := XposedModule
LOCAL_SRC_FILES := XposedModule.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := testkey
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/app
include $(BUILD_PREBUILT)
